#!/bin/bash

# ============================================================================
# REPO SENTRY — As-Built Audit Generator
# ============================================================================
# Run this from your repo root:
#   chmod +x repo-sentry.sh && ./repo-sentry.sh
#
# It collects everything about your repo into a single AUDIT.md file,
# then you can feed that to Claude for commercialization analysis.
# ============================================================================

set -euo pipefail

REPO_ROOT="$(pwd)"
OUTPUT="$REPO_ROOT/AUDIT.md"
TEMP_DIR=$(mktemp -d)

echo "🔍 REPO SENTRY — Scanning $(basename "$REPO_ROOT")…"
echo ""

# ============================================================================
# HEADER
# ============================================================================

cat > "$OUTPUT" << 'EOF'
# AS-BUILT AUDIT REPORT

> Auto-generated by Repo Sentry

-----

EOF

echo "Generated: $(date -u '+%Y-%m-%d %H:%M UTC')" >> "$OUTPUT"
echo "Repo Path: $REPO_ROOT" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ============================================================================
# 1. DIRECTORY TREE (depth 4, ignore noise)
# ============================================================================

echo "## 1. Directory Structure" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
if command -v tree &> /dev/null; then
  tree -L 4 -I 'node_modules|.git|__pycache__|.venv|venv|env|.env|dist|build|.next|*.pyc|.DS_Store|*.egg-info' \
    --dirsfirst "$REPO_ROOT" >> "$OUTPUT" 2>/dev/null || \
  find "$REPO_ROOT" -maxdepth 4 \
    ! -path '*node_modules*' ! -path '*.git/*' ! -path '*__pycache__*' \
    ! -path '*.venv*' ! -path '*venv/*' ! -path '*dist/*' ! -path '*build/*' \
    | head -200 >> "$OUTPUT"
else
  find "$REPO_ROOT" -maxdepth 4 \
    ! -path '*node_modules*' ! -path '*.git/*' ! -path '*__pycache__*' \
    ! -path '*.venv*' ! -path '*venv/*' ! -path '*dist/*' ! -path '*build/*' \
    | head -200 >> "$OUTPUT"
fi
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ============================================================================
# 2. FILE INVENTORY WITH SIZES
# ============================================================================

echo "## 2. File Inventory (by type)" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### File type breakdown:" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
find "$REPO_ROOT" -type f \
  ! -path '*node_modules*' ! -path '*.git/*' ! -path '*__pycache__*' \
  ! -path '*.venv*' ! -path '*venv/*' ! -path '*dist/*' ! -path '*build/*' \
  | sed 's/.*\.//' | sort | uniq -c | sort -rn >> "$OUTPUT" 2>/dev/null || \
  echo "Could not enumerate files" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### Largest files (top 30):" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
find "$REPO_ROOT" -type f \
  ! -path '*node_modules*' ! -path '*.git/*' ! -path '*__pycache__*' \
  ! -path '*.venv*' ! -path '*venv/*' \
  -exec du -h {} + 2>/dev/null | sort -rh | head -30 >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ============================================================================
# 3. DEPENDENCY MANIFESTS
# ============================================================================

echo "## 3. Dependencies & Configuration" >> "$OUTPUT"
echo "" >> "$OUTPUT"

for f in package.json requirements.txt Pipfile pyproject.toml setup.py setup.cfg Cargo.toml go.mod Gemfile composer.json; do
  FOUND=$(find "$REPO_ROOT" -maxdepth 3 -name "$f" ! -path '*node_modules*' ! -path '*.git/*' 2>/dev/null)
  if [ -n "$FOUND" ]; then
    for filepath in $FOUND; do
      echo "### $(basename "$filepath") — \`${filepath#$REPO_ROOT/}\`" >> "$OUTPUT"
      echo '```' >> "$OUTPUT"
      cat "$filepath" >> "$OUTPUT" 2>/dev/null
      echo "" >> "$OUTPUT"
      echo '```' >> "$OUTPUT"
      echo "" >> "$OUTPUT"
    done
  fi
done

# ============================================================================
# 4. ENVIRONMENT VARIABLES & CONFIG FILES
# ============================================================================

echo "## 4. Environment & Config (keys redacted)" >> "$OUTPUT"
echo "" >> "$OUTPUT"

for f in .env.example .env.sample .env.template docker-compose.yml docker-compose.yaml Dockerfile Makefile; do
  FOUND=$(find "$REPO_ROOT" -maxdepth 3 -name "$f" ! -path '*node_modules*' 2>/dev/null)
  if [ -n "$FOUND" ]; then
    for filepath in $FOUND; do
      echo "### \`${filepath#$REPO_ROOT/}\`" >> "$OUTPUT"
      echo '```' >> "$OUTPUT"
      # Redact anything that looks like a secret
      sed -E 's/(KEY|SECRET|TOKEN|PASSWORD|PASS|API_KEY|AUTH|CREDENTIAL)=.*/\1=<REDACTED>/gi' "$filepath" >> "$OUTPUT" 2>/dev/null
      echo '```' >> "$OUTPUT"
      echo "" >> "$OUTPUT"
    done
  fi
done

# Also check for actual .env (redact all values)
if [ -f "$REPO_ROOT/.env" ]; then
  echo "### \`.env\` (all values redacted)" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  sed -E 's/=.*/=<REDACTED>/' "$REPO_ROOT/.env" >> "$OUTPUT" 2>/dev/null
  echo '```' >> "$OUTPUT"
  echo "" >> "$OUTPUT"
fi

# ============================================================================
# 5. DATABASE SCHEMAS & MIGRATIONS
# ============================================================================

echo "## 5. Database Schemas & Data Models" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# SQL files
SQL_FILES=$(find "$REPO_ROOT" -maxdepth 5 -name "*.sql" ! -path '*node_modules*' ! -path '*.git/*' 2>/dev/null || true)
if [ -n "$SQL_FILES" ]; then
  echo "### SQL Files:" >> "$OUTPUT"
  for filepath in $SQL_FILES; do
    echo "#### \`${filepath#$REPO_ROOT/}\`" >> "$OUTPUT"
    echo '```sql' >> "$OUTPUT"
    head -200 "$filepath" >> "$OUTPUT" 2>/dev/null
    echo '```' >> "$OUTPUT"
    echo "" >> "$OUTPUT"
  done
fi

# Migration files
MIGRATION_DIRS=$(find "$REPO_ROOT" -maxdepth 4 -type d -name "migrations" ! -path '*node_modules*' ! -path '*.git/*' 2>/dev/null || true)
if [ -n "$MIGRATION_DIRS" ]; then
  echo "### Migration directories found:" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  for d in $MIGRATION_DIRS; do
    ls -la "$d" >> "$OUTPUT" 2>/dev/null
  done
  echo '```' >> "$OUTPUT"
  echo "" >> "$OUTPUT"
fi

# SQLite or DB files
DB_FILES=$(find "$REPO_ROOT" -maxdepth 4 \( -name "*.db" -o -name "*.sqlite" -o -name "*.sqlite3" \) ! -path '*node_modules*' 2>/dev/null || true)
if [ -n "$DB_FILES" ]; then
  echo "### Database files found:" >> "$OUTPUT"
  for dbfile in $DB_FILES; do
    echo "- \`${dbfile#$REPO_ROOT/}\` ($(du -h "$dbfile" | cut -f1))" >> "$OUTPUT"
    if command -v sqlite3 &> /dev/null; then
      echo '```sql' >> "$OUTPUT"
      echo "-- Tables:" >> "$OUTPUT"
      sqlite3 "$dbfile" ".tables" >> "$OUTPUT" 2>/dev/null || echo "(could not read)" >> "$OUTPUT"
      echo "" >> "$OUTPUT"
      echo "-- Schema:" >> "$OUTPUT"
      sqlite3 "$dbfile" ".schema" >> "$OUTPUT" 2>/dev/null || echo "(could not read)" >> "$OUTPUT"
      echo '```' >> "$OUTPUT"
    fi
    echo "" >> "$OUTPUT"
  done
fi

# ============================================================================
# 6. DATA FILES (CSV, JSON, JSONL, Parquet, etc.)
# ============================================================================

echo "## 6. Data Assets" >> "$OUTPUT"
echo "" >> "$OUTPUT"

DATA_FILES=$(find "$REPO_ROOT" -maxdepth 5 \
  \( -name "*.csv" -o -name "*.json" -o -name "*.jsonl" -o -name "*.parquet" \
  -o -name "*.xlsx" -o -name "*.tsv" -o -name "*.yaml" -o -name "*.yml" \) \
  ! -path '*node_modules*' ! -path '*.git/*' ! -path '*package*.json' \
  ! -name "tsconfig.json" ! -name ".prettierrc*" ! -name ".eslintrc*" \
  2>/dev/null || true)

if [ -n "$DATA_FILES" ]; then
  for filepath in $DATA_FILES; do
    SIZE=$(du -h "$filepath" | cut -f1)
    LINES=$(wc -l < "$filepath" 2>/dev/null || echo "?")
    echo "### \`${filepath#$REPO_ROOT/}\` ($SIZE, $LINES lines)" >> "$OUTPUT"
    echo '```' >> "$OUTPUT"
    # Show first 30 lines for data files
    head -30 "$filepath" >> "$OUTPUT" 2>/dev/null
    TOTAL=$(wc -l < "$filepath" 2>/dev/null || echo 0)
    if [ "$TOTAL" -gt 30 ] 2>/dev/null; then
      echo "... ($TOTAL total lines)" >> "$OUTPUT"
    fi
    echo '```' >> "$OUTPUT"
    echo "" >> "$OUTPUT"
  done
else
  echo "*No standalone data files found.*" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
fi

# ============================================================================
# 7. API ROUTES & ENDPOINTS
# ============================================================================

echo "## 7. API Routes & Endpoints" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### Route definitions found:" >> "$OUTPUT"
echo '```' >> "$OUTPUT"

# Flask/FastAPI/Express routes
grep -rn --include="*.py" --include="*.js" --include="*.ts" \
  -E '(@app\.(get|post|put|delete|patch|route)|@router\.(get|post|put|delete|patch)|app\.(get|post|put|delete|patch|use)\(|@api_view)' \
  "$REPO_ROOT" \
  --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=venv --exclude-dir=__pycache__ \
  2>/dev/null | head -100 >> "$OUTPUT" || echo "No routes found" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ============================================================================
# 8. LLM / AI INTEGRATION POINTS
# ============================================================================

echo "## 8. AI/LLM Integration Points" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "### AI-related imports and calls:" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
grep -rn --include="*.py" --include="*.js" --include="*.ts" \
  -iE '(openai|anthropic|claude|gpt|llm|langchain|vision|image.*analy|ocr|tesseract|ollama|hugging|transformers|torch|tensorflow|keras)' \
  "$REPO_ROOT" \
  --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=venv --exclude-dir=__pycache__ \
  2>/dev/null | head -80 >> "$OUTPUT" || echo "No AI integrations found" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ============================================================================
# 9. EXTERNAL API CALLS
# ============================================================================

echo "## 9. External API Calls & Integrations" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo '```' >> "$OUTPUT"
grep -rn --include="*.py" --include="*.js" --include="*.ts" \
  -E '(requests\.(get|post|put)|fetch\(|axios\.|http\.request|urllib|aiohttp|httpx)' \
  "$REPO_ROOT" \
  --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=venv --exclude-dir=__pycache__ \
  2>/dev/null | head -60 >> "$OUTPUT" || echo "No external API calls found" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Also look for base URLs / API endpoints
echo "### Hardcoded API URLs:" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
grep -rn --include="*.py" --include="*.js" --include="*.ts" --include="*.env*" \
  -oE 'https?://api\.[a-zA-Z0-9._/-]+' \
  "$REPO_ROOT" \
  --exclude-dir=node_modules --exclude-dir=.git --exclude-dir=venv \
  2>/dev/null | sort -u | head -30 >> "$OUTPUT" || echo "None found" >> "$OUTPUT"
echo '```' >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ============================================================================
# 10. KEY SOURCE FILES (full content of core modules)
# ============================================================================

echo "## 10. Key Source Files (full content)" >> "$OUTPUT"
echo "" >> "$OUTPUT"
echo "*Showing all .py, .js, .ts files under 300 lines (excluding tests/configs):*" >> "$OUTPUT"
echo "" >> "$OUTPUT"

find "$REPO_ROOT" -maxdepth 5 \( -name "*.py" -o -name "*.js" -o -name "*.ts" -o -name "*.jsx" -o -name "*.tsx" \) \
  ! -path '*node_modules*' ! -path '*.git/*' ! -path '*__pycache__*' \
  ! -path '*.venv*' ! -path '*venv/*' ! -path '*dist/*' ! -path '*build/*' \
  ! -path '*test*' ! -path '*spec*' ! -name "*.config.*" ! -name "*.test.*" \
  2>/dev/null | sort | while read -r filepath; do
  LINES=$(wc -l < "$filepath" 2>/dev/null || echo 999)
  EXT="${filepath##*.}"
  if [ "$LINES" -le 300 ]; then
    echo "### \`${filepath#$REPO_ROOT/}\` ($LINES lines)" >> "$OUTPUT"
    echo '```'"$EXT" >> "$OUTPUT"
    cat "$filepath" >> "$OUTPUT" 2>/dev/null
    echo '```' >> "$OUTPUT"
    echo "" >> "$OUTPUT"
  else
    echo "### \`${filepath#$REPO_ROOT/}\` ($LINES lines — showing first/last 50)" >> "$OUTPUT"
    echo '```'"$EXT" >> "$OUTPUT"
    head -50 "$filepath" >> "$OUTPUT" 2>/dev/null
    echo "" >> "$OUTPUT"
    echo "# ... ($(($LINES - 100)) lines omitted) ..." >> "$OUTPUT"
    echo "" >> "$OUTPUT"
    tail -50 "$filepath" >> "$OUTPUT" 2>/dev/null
    echo '```' >> "$OUTPUT"
    echo "" >> "$OUTPUT"
  fi
done

# ============================================================================
# 11. README & DOCS
# ============================================================================

echo "## 11. Documentation" >> "$OUTPUT"
echo "" >> "$OUTPUT"

for f in README.md README.rst README.txt README CONTRIBUTING.md CHANGELOG.md; do
  FOUND=$(find "$REPO_ROOT" -maxdepth 2 -name "$f" ! -path '*node_modules*' 2>/dev/null || true)
  if [ -n "$FOUND" ]; then
    for filepath in $FOUND; do
      if [ -f "$filepath" ]; then
        echo "### \`${filepath#$REPO_ROOT/}\`" >> "$OUTPUT"
        echo '```' >> "$OUTPUT"
        cat "$filepath" >> "$OUTPUT" 2>/dev/null
        echo '```' >> "$OUTPUT"
        echo "" >> "$OUTPUT"
      fi
    done
  fi
done

# ============================================================================
# 12. GIT HISTORY SUMMARY
# ============================================================================

echo "## 12. Git History Summary" >> "$OUTPUT"
echo "" >> "$OUTPUT"

if [ -d "$REPO_ROOT/.git" ]; then
  echo "### Recent commits (last 30):" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  git -C "$REPO_ROOT" log --oneline --decorate -30 >> "$OUTPUT" 2>/dev/null || echo "Could not read git log" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  echo "" >> "$OUTPUT"

  echo "### Contributors:" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  git -C "$REPO_ROOT" shortlog -sn --all >> "$OUTPUT" 2>/dev/null || echo "Could not read contributors" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  echo "" >> "$OUTPUT"

  echo "### Total commits:" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  git -C "$REPO_ROOT" rev-list --all --count >> "$OUTPUT" 2>/dev/null || echo "?" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  echo "" >> "$OUTPUT"

  echo "### Branches:" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  git -C "$REPO_ROOT" branch -a >> "$OUTPUT" 2>/dev/null || echo "Could not list branches" >> "$OUTPUT"
  echo '```' >> "$OUTPUT"
  echo "" >> "$OUTPUT"
else
  echo "*No git repository found.*" >> "$OUTPUT"
  echo "" >> "$OUTPUT"
fi

# ============================================================================
# 13. SUMMARY STATS
# ============================================================================

echo "## 13. Summary Stats" >> "$OUTPUT"
echo "" >> "$OUTPUT"

TOTAL_FILES=$(find "$REPO_ROOT" -type f ! -path '*node_modules*' ! -path '*.git/*' ! -path '*__pycache__*' ! -path '*.venv*' 2>/dev/null | wc -l)
TOTAL_CODE_LINES=$(find "$REPO_ROOT" -type f \( -name "*.py" -o -name "*.js" -o -name "*.ts" -o -name "*.jsx" -o -name "*.tsx" \) ! -path '*node_modules*' ! -path '*.git/*' ! -path '*__pycache__*' ! -path '*.venv*' 2>/dev/null -exec cat {} + 2>/dev/null | wc -l)
TOTAL_DATA_FILES=$(find "$REPO_ROOT" -type f \( -name "*.csv" -o -name "*.json" -o -name "*.jsonl" -o -name "*.parquet" -o -name "*.xlsx" \) ! -path '*node_modules*' ! -path '*.git/*' ! -name "package*.json" ! -name "tsconfig.json" 2>/dev/null | wc -l)
REPO_SIZE=$(du -sh "$REPO_ROOT" --exclude=node_modules --exclude=.git 2>/dev/null | cut -f1 || du -sh "$REPO_ROOT" 2>/dev/null | cut -f1)

cat >> "$OUTPUT" << EOF
| Metric                 | Value            |
|------------------------|------------------|
| Total files            | $TOTAL_FILES     |
| Lines of code          | $TOTAL_CODE_LINES|
| Data files             | $TOTAL_DATA_FILES|
| Repo size (excl. deps) | $REPO_SIZE       |
EOF

echo "" >> "$OUTPUT"

# ============================================================================
# DONE
# ============================================================================

echo "" >> "$OUTPUT"
echo "---" >> "$OUTPUT"
echo "*End of audit. Feed this file to Claude for commercialization analysis.*" >> "$OUTPUT"

rm -rf "$TEMP_DIR"

echo "✅ AUDIT COMPLETE"
echo ""
echo "📄 Output: $OUTPUT"
echo "📊 Stats: $TOTAL_FILES files | $TOTAL_CODE_LINES lines of code | $TOTAL_DATA_FILES data files"
echo ""
echo "Next step: Open a new Claude conversation and paste/upload AUDIT.md with the prompt:"
echo ""
echo '  "Here is the as-built audit of my allergen detection app repo.'
echo '   I have LLM vision for food image analysis, allergen/chemical compound'
echo '   data tables, and recipe API integrations. I could not commercialize'
echo '   due to food delivery image licensing and liability concerns.'
echo '   Analyze every asset and give me the top 3 commercial pivots'
echo '   that reuse the most existing code and data."'
echo ""
