import React, { useState, useRef } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  Modal,
  StyleSheet,
  Animated,
  Dimensions,
  Pressable,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import {
  LEGAL_COLORS,
  LEGAL_TYPOGRAPHY,
  LEGAL_SPACING,
  LEGAL_RADIUS,
  LEGAL_ANIMATIONS,
} from './legalDesignSystem';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

type TooltipType = 'calorie' | 'macro' | 'allergen' | 'organ' | 'ai' | 'custom';

interface TooltipContent {
  title: string;
  body: string;
  icon: keyof typeof Ionicons.glyphMap;
}

const TOOLTIP_CONTENT: Record<Exclude<TooltipType, 'custom'>, TooltipContent> = {
  calorie: {
    title: 'Calorie Estimates',
    body: 'Daily calorie targets are estimates based on your profile. Individual needs vary significantly. Consult a healthcare provider or registered dietitian for personalized recommendations.',
    icon: 'flame-outline',
  },
  macro: {
    title: 'Macronutrient Data',
    body: 'Nutritional values are estimates from third-party databases and AI analysis. Actual values may vary based on portion sizes, preparation methods, and ingredient substitutions.',
    icon: 'pie-chart-outline',
  },
  allergen: {
    title: 'Allergen Information',
    body: 'Allergen data may be incomplete or inaccurate. Cross-contamination can occur in restaurant kitchens. Always verify ingredients directly with the restaurant if you have food allergies.',
    icon: 'warning-outline',
  },
  organ: {
    title: 'Organ Health Scores',
    body: 'Organ health assessments are based on general nutritional research and your profile settings. They are not diagnostic and should not replace professional medical evaluation.',
    icon: 'body-outline',
  },
  ai: {
    title: 'AI-Generated Content',
    body: 'This content was generated by AI and may contain errors or inaccuracies. AI recommendations are for informational purposes only and should be independently verified.',
    icon: 'sparkles-outline',
  },
};

interface InfoIconTooltipProps {
  type: TooltipType;
  customTitle?: string;
  customBody?: string;
  size?: number;
  color?: string;
  style?: object;
}

export function InfoIconTooltip({
  type,
  customTitle,
  customBody,
  size = 16,
  color = LEGAL_COLORS.textMuted,
  style,
}: InfoIconTooltipProps) {
  const [visible, setVisible] = useState(false);
  const fadeAnim = useRef(new Animated.Value(0)).current;
  const scaleAnim = useRef(new Animated.Value(0.9)).current;

  const content = type === 'custom'
    ? { title: customTitle || 'Info', body: customBody || '', icon: 'information-circle-outline' as const }
    : TOOLTIP_CONTENT[type];

  const showTooltip = () => {
    setVisible(true);
    Animated.parallel([
      Animated.timing(fadeAnim, {
        toValue: 1,
        duration: LEGAL_ANIMATIONS.tooltipAppear,
        useNativeDriver: true,
      }),
      Animated.spring(scaleAnim, {
        toValue: 1,
        friction: 8,
        tension: 40,
        useNativeDriver: true,
      }),
    ]).start();
  };

  const hideTooltip = () => {
    Animated.parallel([
      Animated.timing(fadeAnim, {
        toValue: 0,
        duration: LEGAL_ANIMATIONS.tooltipAppear,
        useNativeDriver: true,
      }),
      Animated.timing(scaleAnim, {
        toValue: 0.9,
        duration: LEGAL_ANIMATIONS.tooltipAppear,
        useNativeDriver: true,
      }),
    ]).start(() => setVisible(false));
  };

  return (
    <>
      <TouchableOpacity
        onPress={showTooltip}
        style={[styles.iconButton, style]}
        hitSlop={{ top: 10, bottom: 10, left: 10, right: 10 }}
      >
        <Ionicons name="information-circle-outline" size={size} color={color} />
      </TouchableOpacity>

      <Modal
        visible={visible}
        transparent
        animationType="none"
        statusBarTranslucent
        onRequestClose={hideTooltip}
      >
        <Pressable style={styles.overlay} onPress={hideTooltip}>
          <Animated.View
            style={[
              styles.tooltipContainer,
              {
                opacity: fadeAnim,
                transform: [{ scale: scaleAnim }],
              },
            ]}
          >
            <View style={styles.tooltipHeader}>
              <Ionicons
                name={content.icon}
                size={20}
                color={LEGAL_COLORS.primaryTeal}
              />
              <Text style={styles.tooltipTitle}>{content.title}</Text>
              <TouchableOpacity onPress={hideTooltip} style={styles.closeButton}>
                <Ionicons name="close" size={20} color={LEGAL_COLORS.textMuted} />
              </TouchableOpacity>
            </View>
            <Text style={styles.tooltipBody}>{content.body}</Text>
          </Animated.View>
        </Pressable>
      </Modal>
    </>
  );
}

// Inline info text with icon (no modal)
interface InfoTextInlineProps {
  text: string;
  style?: object;
}

export function InfoTextInline({ text, style }: InfoTextInlineProps) {
  return (
    <View style={[styles.inlineContainer, style]}>
      <Ionicons
        name="information-circle-outline"
        size={14}
        color={LEGAL_COLORS.textInfo}
        style={styles.inlineIcon}
      />
      <Text style={styles.inlineText}>{text}</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  iconButton: {
    padding: LEGAL_SPACING.xs,
  },
  overlay: {
    flex: 1,
    backgroundColor: LEGAL_COLORS.overlayBg,
    justifyContent: 'center',
    alignItems: 'center',
    padding: LEGAL_SPACING.xl,
  },
  tooltipContainer: {
    backgroundColor: LEGAL_COLORS.cardBg,
    borderRadius: LEGAL_RADIUS.lg,
    padding: LEGAL_SPACING.lg,
    width: '100%',
    maxWidth: SCREEN_WIDTH - LEGAL_SPACING.xl * 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  tooltipHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: LEGAL_SPACING.md,
  },
  tooltipTitle: {
    ...LEGAL_TYPOGRAPHY.sectionTitle,
    flex: 1,
    marginLeft: LEGAL_SPACING.sm,
  },
  closeButton: {
    padding: LEGAL_SPACING.xs,
  },
  tooltipBody: {
    ...LEGAL_TYPOGRAPHY.body,
    lineHeight: 22,
  },
  // Inline styles
  inlineContainer: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  inlineIcon: {
    marginRight: LEGAL_SPACING.xs,
    marginTop: 1,
  },
  inlineText: {
    ...LEGAL_TYPOGRAPHY.inlineDisclaimer,
    flex: 1,
  },
});

export default InfoIconTooltip;
